[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name         tail
    Path         /opt/airflow/logs/*/*/*.log
    Tag          airflow.logs

[OUTPUT]
    Name         loki
    Match        *
    Host         loki
    Port         3100
    Labels       job=airflow, university_project=marwat_lab
